### ISSUE TITLE
Add argument for EF endpoint

### ISSUE THREAD

**Issue by JaimieMurdock** [htrc/htrc-feature-reader#23]
If a user has a complete local mirror, they should be able to use that instead of the ''data.analytics.hathitrust.org" URL for the download_file and FeatureReader `DL_URL`.

- [ ] [`htrc_features.utils`](https://github.com/htrc/htrc-feature-reader/blob/master/htrc_features/utils.py)
- [ ] [`htrc_features.FeatureReader`](https://github.com/htrc/htrc-feature-reader/blob/master/htrc_features/feature_reader.py)

This also could be used to check a local cache if the json files are already downloaded.

**Comment by organisciak** [comment]
Why not just load the regular way, giving `FeatureReader` a file location or iterable of file locations?

Is your request:
1) to combine the hathi id -> file path with local paths, so you can use just the ids on your local system (if you have the exact same pairtree structure) 
or
2) to allow changing the URL to other remote locations?

I suppose there's possible merit to both readings...
