### ISSUE TITLE
Remove ujson dependency from setup.py?

### ISSUE THREAD

**Issue by bmschmidt** [htrc/htrc-feature-reader#31]
Trying to install on a wonky machine, I found I had to manually remove the entry for ujson from setup.py because I was having trouble compiling it.

In general, ujson [is a dead package](https://github.com/tiangolo/fastapi/issues/820); it might be worth switching to [`orjson` for speed](https://pythonspeed.com/articles/faster-json-library/). But since there's already a fallback to standard `json` in the code here, I don't think it would hurt to just remove it from the setup?

**Comment by organisciak** [comment]
I'll update this in the Massive Texts fork, since I'll be looking to merge that here in the coming month or so. `orjson` looks good - the built-in library was a bottleneck. The side benefit is that I can stop maintaining a conda package for ujson!

**Comment by organisciak** [comment]
... but looks like I'll have to build an orjson conda package.

**Comment by organisciak** [comment]
Updated https://github.com/massivetexts/htrc-feature-reader/commit/7eae68aa368f3e1bc41b36a4f504f8bbe6ff46c8 with rapidjson, which seems better supported.
