### ISSUE TITLE
Option to suppress printing of paths/ids at FeatureReader instantiation

### ISSUE THREAD

**Issue by wilkens** [htrc/htrc-feature-reader#35]
Using v. 2.05 of the FeatureReader class, a complete list of paths or IDs is printed on FeatureReader initialization. This is awkward if the list of files/IDs is long, and may not be all that helpful in any case. Might it be suppressed? Or made into an option (suggest off by default)?

Thanks. Otherwise, version 2 seems to be working well for me so far.

**Comment by organisciak** [comment]
Ah, thanks so much! Tests don't catch that and I was too focused on the new loading via 'Volume(htid)' that I overlooked the errant printing with 'FeatureReader(htids)'. Will push out an update soon.

**Comment by organisciak** [comment]
And it's errant debugging, so will just remove it outright rather than suppressing.
