### ISSUE TITLE
syntax error in htrc_features/feature_downloader.py

### ISSUE THREAD

**Issue by keithfma** [htrc/htrc-feature-reader#4]
I was trying to build a conda recipie for this package, and encountered a syntax error in htrc_features/feature_downloader.py. The logging.error() call is missing the closing parenthesis. After patching this file, I was able to build successfully.

Best,
Keith Ma

**Comment by organisciak** [comment]
Oh goodness, I couldn't figure this out, there never was a `feature_downloader.py` in the repo. I had a placeholder file on my system (which doesn't do anything yet!), and I suppose I inadvertently built it into the distribution. I'll correct that.

**Comment by organisciak** [comment]
I believe I removed that junk file in distribution `1.42`, but I'll need to reinstall my testing environment on my new computer to try a clean install. I'll confirm this evening.

**Comment by keithfma** [comment]
Thanks, much appreciated.

**Comment by organisciak** [comment]
Seems to be fixed.
