### ISSUE TITLE
Docs are not found

### ISSUE THREAD

**Issue by keithfma** [htrc/htrc-feature-reader#5]
Hello,

The documentation pages do not appear to be working. When I attempt to navigate to...

http://organisciak.github.io/htrc-feature-reader/htrc_features/feature_reader.m.html

...or any of the subpages, I get a 404 error.

Many Thanks,
Keith

**Comment by organisciak** [comment]
Thank you. This is because I transferred the account from my personal
account (organisciak) to the htrc organisational account a few days ago. I
didn't know that Github doesn't auto-forward.

**Comment by organisciak** [comment]
Fixed with 24bcfae6a4ffc587579be44370777cc404421b65
